### ISSUE TITLE
Object compatibility. Json

### ISSUE THREAD

**Issue by Snickthepork** [Mitchell1711/pt-cyop#1]
Game keeps shouting at me that object compatibility.json isn't in the editor assets folder. Tried to make my own, game opened but spits me an error when I open tower

**Comment by LocalVoidedFox** [comment]
It should be naturally included in the data folder.

**Comment by Snickthepork** [comment]
It wasnt

**Comment by LocalVoidedFox** [comment]
![Screenshot 2024-04-18 131633](https://github.com/Mitchell1711/pt-cyop/assets/55364498/64886f32-63b7-4e33-9c1a-793359b8cc3b)

It should be

**Comment by Snickthepork** [comment]
Oh nvm
