### ISSUE TITLE
Randomly hurt for no reason

### ISSUE THREAD

**Issue by LocalVoidedFox** [Mitchell1711/pt-cyop#2]
While playing through a CYOP level, sometimes the game will think you got hit by something even though there might not be anything dangerous at all, and your combo meter will even drop because of it.

https://github.com/Mitchell1711/pt-cyop/assets/55364498/c11144c6-4551-4236-91dc-c2f0f9df298a

**Comment by LocalVoidedFox** [comment]
I'm not sure how one would replicate this bug since it happens randomly for no reason.

**Comment by EmeraldMan25** [comment]
I think this might be fixed but this was caused by things hitting obj_player2, which is stored out of bounds. Very weird error overall

**Comment by Mitchell1711** [comment]
Yeah what @EmeraldMan25 mentioned, not sure why it's not in the original CYOP either but I just added some code to exit the hurt code for obj_player2 so it should hopefully be fixed (I couldn't reproduce it anymore at least but it's hard to tell with this bug)

**Comment by LocalVoidedFox** [comment]
I think I figured out why I was being hurt, Other Tower places Goblin Cannons out of sight which makes up the illusion of how getting Greaseball into the goal increases your time. I've removed Pillar John but apparently, somehow these Goblin Cannons hurt, somehow.

(This video was recorded in the v2 xDelta patch)

[Other Tower](https://gamebanana.com/mods/446545)

https://github.com/Mitchell1711/pt-cyop/assets/55364498/4ffd55fd-6abf-4e12-ab58-c398b6d3f9d9
