### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Michaelthjgg** [Mitchell1711/pt-cyop#5]
![image_2024-04-27_003541059](https://github.com/Mitchell1711/pt-cyop/assets/150302748/e37234ca-389f-4f2e-bdd2-623777cc2b43)
when i try to open it it says this

**Comment by Mitchell1711** [comment]
What files are in your Pizza Tower lang folder (Program Files (x86)\Steam\steamapps\common\Pizza Tower\lang)? Also could you revert the data.win back to the original and check if the vanilla game also crashes on startup.

**Comment by Michaelthjgg** [comment]
wait nvm i fixed it
